### PR TITLE
Add customizable CSS (closes #16)

### LINKED ISSUE #16: Please add dark mode
With https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

### PR DESCRIPTION
**Pull request by andy5995**
By adding a Gemfile, I can test changes locally by running 'bundle exec jekyll serve'

```
bundle init
echo 'gem "github-pages", group: :jekyll_plugins' >> Gemfile
bundle install
```

image

If there is some other way to test locally without using a Gemfile, please let me know, and then we can skip adding the Gemfile.

The next step I'll try is to alter the css.

### CODE REVIEW

**Comment by andy5995** [comment]
Using commit https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/pull/19/commits/6c55a3201bdc4380ecfbc2cce9dced8b582d3e8d I changed the links to green (for testing, temporary purposes only)

image

**Comment by andy5995** [comment]
image

image

**Comment by andy5995** [comment]
What do you think @vitaly-zdanevich

image

**Comment by andy5995** [comment]
I used ChatGPT to generate the CSS @ivan-hc  I don't write CSS very often and it would take me forever to look up how to do it.

**Comment by ivan-hc** [comment]
its great, but consider using light blue as a color instead of yellow... or maybe green/light green

**Comment by ivan-hc** [comment]
@andy5995 Huston, we have a problem

Istantanea_2024-10-05_13-10-20 png
Istantanea_2024-10-05_13-10-06 png

the spaces for the code is white, and also the text

**Comment by andy5995** [comment]
I'll have a look and try to fix it.

**Pull request merged**
