### PR TITLE
Updating broken/outdated icons

### PR DESCRIPTION
**Pull request by GeoBoi254**
These are the icons I could find for now.

### CODE REVIEW

**Comment by GeoBoi254** [comment]
Just realized I put some of the icons on the main folder, not the icon folder.

**Comment by GeoBoi254** [comment]
This should be it for now.

**Comment by ivan-hc** [comment]
for me its all ok, thanks!

Can I already merge? Or want to add other icons?

**Comment by GeoBoi254** [comment]
Go ahead and merge it.

**Comment by ivan-hc** [comment]
Thank you very much! I hope to see more contributions like this! Really appreciate! :pray:

**Pull request merged**
