### PR TITLE
_config.yml: Replace name with title, add a few other items (closes #24)

### LINKED ISSUE #24: Warning that site.title should be used instead
When I test the site with Jekyll, I get the warning:

>GitHub Metadata: site.name is set in _config.yml, but many plugins and themes expect site.title to be used instead. To avoid potential inconsistency, Jekyll GitHub Metadata will not set site.title to the repository's name.

### PR DESCRIPTION
**Pull request by andy5995**
Some of what I did here won't really change anything but may come in useful later and I don't think it'll harm anything in the meantime.

The @jekyll docs here list some configuration options, but I have absolutely no idea why "title" isn't mentioned on this page https://jekyllrb.com/docs/configuration/options/#build-command-options nor why it's not mentioned on the page titled "Default configuration" at https://jekyllrb.com/docs/configuration/default/

When I ran 'jekyll new .' locally it gave me this _config.yml

```
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
```

### CODE REVIEW

**Comment by ivan-hc** [comment]
this change adds a button on top of the pages :skull:  ... I want to get rid of it

**Comment by andy5995** [comment]
> this change adds a button on top of the pages 💀 ... I want to get rid of it

Oops.. I'll fix it now.

**Comment by ivan-hc** [comment]
done, I reverted from "title" to "name"

**Comment by andy5995** [comment]
I can try to explain why that happened. jekyll-theme-primer is set to be the them in _config.yml. When the site builds, variables from the config are automatically used and displayed with the theme.

On my PC, the theme files are located here:

image

So when I build the site, it uses those files. When you publish to Github, the theme is stored on GitHub pages.

If you ever want more flexibility for your theme, you can customize it pretty easily https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#customizing-your-themes-html-layout

In that example, they use the minimal theme, but the primer theme is at https://github.com/pages-themes/primer

Anyway, it's nothing to give thought to right now unless you really want to customize the theme. But there is the info if you ever want it. I hope I helped a little. :)

**Comment by ivan-hc** [comment]
thanks

**Pull request merged**
