### PR TITLE
update altair.md antares.md cemu.md add butterfly.md

### PR DESCRIPTION
**Pull request by Drsheppard01**
According this PR i want to ask about link on https://raw.githubusercontent.com/ivan-hc/AM-Application-Manager/main/programs/x86_64/
Do I understand correctly that you build packages using your own recipes instead of the ones provided by the developers?

### CODE REVIEW

**Comment by ivan-hc** [comment]
"butterfly" already exists as "linwood-butterfly"

**Comment by ivan-hc** [comment]
why have you enshorted cemu's description?

**Comment by Drsheppard01** [comment]
> "butterfly" already exists as "linwood-butterfly"

perhaps it should be renamed butterfly?

> why have you enshorted cemu's description?

I put the description from the [github project](cemu-project/Cemu). I find it more concise

**Comment by ivan-hc** [comment]
> perhaps it should be renamed butterfly?

this is what we found when searching it on Google

Istantanea_2023-09-29_15-16-24

so nope

> I put the description from the [github project](https://github.com/cemu-project/Cemu). I find it more concise

this is OK for a quick search on a list, not for a whole web page, this should be a first approach for the users to know what they are using (and also, each page is shown in "AM" and AppMan with the option `-a`)

**Review by ivan-hc — APPROVED** [review]

**Pull request merged**
