### PR TITLE
huge maintainance update

### PR DESCRIPTION
**Pull request by Drsheppard01**
Rename: 

- [x] atsdb >> COMPASS
- [x] BITBOX-WALLET-APP-APPIMAGE >> bitbox-wallet
- [x] blockstream-green-appimage >> blockstream-green
- [x] coolero >> CoolerControl
- [x] defi-app-bin >> defichain-app
- [x] FREECAD-ASSEMGLY3 >> FREECAD-ASSEMBLY3
- [x] GETSWELL >> Swell
- [x] Gulden >> Munt
- [x] negibox >> Hapee
- [x] purei >> play!
- [x] rats-on-the-boat >> rats-search (i'm find rats-search.md w/o header and just delete duplicate
- [x] upscayl-appimage >> upscayl

Update links:

- [x] balkarjun/downline >> stefnotch/downline 
- [x] https://github.com/ente-io/bhari-frame >> https://github.com/ente-io/photos-desktop
- [x] https://gdevelop-app.com >> https://gdevelop.io/
- [x] https://gdevs.io >> https://gdlauncher.com/
- [x] https://github.com/getswell/getswell >> https://github.com/open-source-labs/Swell
- [x] Guilden/guilden >> muntorg/munt-official
- [x] https://github.com/digimezzo/knowte-electron >> https://github.com/digimezzo/knowte
- [ ] https://github.com/martinribelotta/launcher >> https://gitlab.com/martinribelotta/launcher
- [x] https://lbry.tech/ >> https://lbry.com/
- [x] https://github.com/LedgerHQ/ledger-live-desktop >>  https://www.ledger.com/ledger-live
- [x] https://librewolf-community.gitlab.io/ >> https://librewolf.net/
- [x] https://github.com/hugetiny/negibox >> https://github.com/hugetiny/Hapee
- [x] https://github.com/mujx/nheko >> https://github.com/Nheko-Reborn/nheko | switch to fork
- [x] https://nofwl.com/ >> https://github.com/lencx/nofwl | github is more informative
- [x] https://numara.io/ >> https://github.com/bornova/numara-calculator | github is more informative
- [x] https://github.com/aferrero2707/rt-build >> https://rawtherapee.com/shared/builds/linux/RawTherapee_5.9.AppImage
- [x] serialplot | https://hackaday.io/ >> https://hackaday.io/project/5334-serialplot-realtime-plotting-software
- [x] https://github.com/atomery/singlebox >> https://singlebox.app/en/
- [x] https://github.com/standardnotes/desktop >> https://github.com/standardnotes/app
- [x] streamcapture | https://www.videohelp.com/  >> https://gitlab.com/posktomten/streamcapture2
- [x] https://structure.love/ >> https://github.com/neopostmodern/structure
- [x] https://www.npmjs.com/package/@ptkdev/svelte-electron-boilerplate >> https://github.com/ptkdev-boilerplate/svelte-electron-boilerplate
- [x] https://github.com/thinreports/thinreports >> https://github.com/thinreports/thinreports-section-editor/
- [x] http://pliablepixels.github.io/ >> https://zmninja.zoneminder.com/
- [x] https://github.com/zulip/zulip-electron >> https://github.com/zulip/zulip-desktop

Delete:

- [ ] accessimap-lecteur-der | Unmaintained
- [ ] adb | no appimage for current versions
- [ ] ai-bot-workspace | Unmaintained
- [ ] Ailio-TS | Unmaintained
- [ ] airspaces | Unmaintained
- [ ] akasha
- [ ] alduin 
- [x] ALVA-APPIMAGE | relink in site (looks like not available anymore)
- [ ] amusiz | unmaintained
- [ ] android-messages-desktop
- [ ] ant-downloader
- [x] ao | Unmaintained, fork kuro is available
- [ ] Aphelion wallet | Unmaintained
- [ ] apla | Unmaintained
- [ ] appimagekit | need separate to appimagetool, appimageupdatetool and pkg2appimage
- [ ] ark | Unmaintained
- [ ] ark.desktop.wallet | Unmaintained
- [ ] around | Unavailable (no info in site, but link is working)
- [ ] asar ui | Unmaintained
- [ ] astroffers | Unmaintained
- [x] astroshooter
- [ ] asunder | appimage not available in current versions
- [ ] audacious  | appimage not available in current versions
- [ ] audmonkey | Unmaintained
- [ ] augur | Unmaintained
- [ ] auryo | Unmaintained
- [ ] autoedit2 | Unmaintained
- [ ] axe-electrum | Unmaintained
- [ ] baijimangaviewer | Unmaintained
- [ ] bezique | Unmaintained
- [ ] billard-gl
- [ ] bioanimation
- [ ] Biying
- [ ] book-manager
- [ ] bottles | now flatpak-centric
- [ ] bovo
- [ ] brackets-electron | upstream is archieved, community fork is outdated
- [ ] brainverse
- [ ] bscanfftwebcam
- [ ] btop | not provide appimage
- [ ] BTS-CE-Lite | site unavailable
- [ ] buche | Unmaintained
- [ ] bunqdesktop | unmaintained
- [ ] BytespeicherTrayIcon | used qt4 which unmaintained
- [ ] cabal-desktop | unmaintained
- [ ] cadmus | unmaintained
- [ ] CAJViewer-Appimage | no appimage in site
- [ ] calculist | unmaintained
- [ ] capbattleship | no provided appimage
- [ ] carnet | unmaintained
- [ ] carpenters | unmaintained
- [ ] castersoundboard
- [ ] cate-desktop
- [ ] cerebral-debugger
- [ ] chainx-signer
- [ ] chromium-bsu
- [ ] chromium-latest (https://download-chromium.appspot.com/) | provide only source
- [ ] chrysalis-bin
- [ ] ciaa-suite
- [ ] circle-z
- [ ] clementineremote
- [ ] clippy
- [ ] clipr
- [ ] cloud-browser
- [ ] cocomusic
- [ ] code-notes-appimage | updates only dependabot, w/o publish release
- [ ] code-oss | no new builds (we has vscodium in repo)
- [ ] colon
- [ ] color-generator
- [ ] colorstatic-bash
- [ ] comic-reader
- [ ] conduction
- [ ] consoleworkbench
- [ ] cool-retro-term | only macOS builds
- [ ] copytranslator-appimage
- [ ] cordlauncher
- [x] cp-editor | remove, 'cause it's duplicate of cpeditor
- [ ] cpod
- [ ] crg-data-tool
- [ ] cryplicity
- [ ] crypter
- [ ] cryptocam-companion
- [ ] cscrypto
- [ ] customrpc
- [ ] cutepeaks
- [ ] cutevariant
- [ ] dana
- [ ] dashy-app
- [ ] dataset-annotator
- [ ] dawnlightsearch
- [ ] dbet-wallet
- [ ] deadgame-2048
- [ ] deb2appimage
- [ ] dedop-studio
- [ ] deemix-gui-appimage | site unavailable
- [ ] deeptags
- [ ] delir
- [ ] demonizer
- [ ] deployer
- [ ] devdocs-desktop
- [ ] devhub
- [ ] dfdemo
- [ ] dfilemanager
- [x] digitales-klassenzimmer | just fork of jitsi-meet, deleted from flatpak, microsoft, snapcraft
- [ ] dingtalk | arhieved project
- [ ] disass
- [ ] discord-qt-appimage 
- [ ] dockstation
- [ ] dokidokimodmanager
- [ ] doublecmd-gtk | 'cause gtk2 is deprecated
- [ ] dragoman 
- [ ] drill | no appimage version in latest release, deprecated 
- [ ] dukto
- [ ] dvdisaster
- [ ] eaglemode
- [ ] easymercurial
- [ ] edex-ui
- [ ] ehdev-shell
- [ ] eksplode.re
- [ ] elcalc
- [ ] eldumper
- [ ] electron-app-store
- [ ] electron-ssr-appimage
- [ ] electron-wechat
- [ ] electronwmd-appimage
- [ ] electron-xiami
- [ ] electrumfair
- [ ] electrum-nmc
- [ ] elphyre-walletshell
- [ ] elzabrowser
- [ ] emacs
- [ ] embedded-ide
- [ ] ember | appimage no available
- [ ] emoji-keyboard-appimage | umaintained 
- [ ] enoseannotator
- [ ] enve
- [ ] eplee
- [ ] erdesigner
- [ ] erscaffold
- [ ] esearch | no available appimage
- [ ] everinst
- [ ] evoplex
- [ ] exeqt
- [ ] exifcleaner
- [ ] eximchainwallet
- [ ] exportoo
- [ ] extremetuxracer
- [ ] eyestalker
- [ ] fastboot | no available appimage
- [ ] fastqt
- [ ] fat-wallet
- [ ] fchat-appimage
- [ ] f-crm
- [ ] feebas
- [ ] feedseries
- [ ] ff-password-exporter
- [ ] fidias-database-migration-app
- [ ] file-converter
- [ ] filelight
- [ ] filezilla
- [ ] filmulator-gui
- [ ] flawesome
- [ ] flightgear-airports
- [ ] fmradio
- [ ] focuswriter
- [ ] fontlet
- [ ] four
- [ ] foxfolio
- [ ] fractale
- [ ] fraidycat
- [ ] fraktal
- [x] frappe-accounting | duplicate of frappebooks
- [ ] freeman
- [ ] fromscratch
- [ ] fSpy
- [ ] genesis
- [ ] gerbv
- [ ] GetThermal
- [ ] gifcurry
- [ ] githoard
- [ ] glabels-qt
- [ ] gltf-insight 
- [ ] glulxe
- [ ] gl_warp2mp4
- [ ] glyphr-studio-desktop
- [ ] gooboxfileshare
- [ ] gradestats
- [ ] granatier
- [ ] groot
- [ ] gsubs
- [ ] gxc-smart-contract-ide
- [ ] hastyheroes
- [ ] hermesmessenger
- [ ] hexo-client
- [ ] hexoeditor
- [ ] hidpi-fixer
- [x] hoverclock-appimage | no available appimage 
- [ ] hpack
- [ ] htmldoc
- [ ] hugin
- [ ] hyperdex
- [ ] hyperionide
- [ ] hyperspace
- [ ] iagoncloudapp
- [ ] imageplay
- [ ] imapsyncclient
- [x] inochi-creator | no available appimage
- [ ] intiface | deprecated, now main client intiface-central, which no available in appimage
- [ ] Invoice-generator
- [ ] iota1k
- [ ] ipuissance-4d
- [ ] isolate
- [ ] jag
- [ ] james
- [ ] jellyamp
- [ ] jira-timer-menubar
- [ ] jklubtv
- [ ] joindesktop
- [ ] juggernaut
- [ ] jumpfm
- [ ] kade
- [ ] kage
- [ ] kanon
- [ ] kawanime
- [ ] kettleclient
- [ ] keyboardclient
- [ ] keymanager
- [ ] keyrier-json
- [ ] keys
- [ ] kicad-appimage
- [ ] kiibohd-configurator
- [ ] kimitzu-client
- [x] kopiaui | duplicate of Kopia
- [ ] kubeman
- [ ] langly
- [ ] LAN-Share
- [x] lbryio | duplicate of lbry-desktop
- [ ] LCEdit
- [x] le | no available in appimage, abandoned
- [ ] led.custom.palette
- [ ] Lepton
- [ ] Lescovex
- [ ] libassist
- [ ] lightning
- [ ] lightningpeach
- [ ] linux-intel-undervolt-gui
- [ ] liveme-pro-tools
- [ ] local-browser
- [ ] loginized
- [ ] luminance-hdr
- [ ] lxtask | appimage not found
- [ ] magicfountain
- [ ] malice
- [ ] manta
- [ ] mapollage
- [ ] mark-mind
- [ ] marlin-config
- [ ] martian
- [ ] mastervyrn
- [ ] mazesolver
- [ ] m
- [ ] mdl
- [ ] mechvibes
- [ ] media-dupes
- [ ] media_mate
- [ ] mellowplayer
- [ ] miesimulatorgui
- [ ] mindmapp
- [ ] MineTime
- [ ] mini-diary
- [ ] minimal-podcasts-player
- [ ] minions
- [ ] mini-qml
- [ ] mira-backup
- [ ] mirage
- [ ] mki3dgame
- [ ] moarperf
- [ ] mob
- [ ] mockman
- [ ] moniteur-admin
- [ ] moose
- [ ] movie-monad
- [ ] mqttcute
- [ ] Mr.Dclutterer
- [ ] mupdf-appimage
- [ ] musicalypse
- [ ] mutool
- [ ] muwire | official statement
- [ ] mybelka
- [ ] mycrypto
- [ ] my-jira
- [ ] mystiq
- [ ] n3h
- [ ] nanovault
- [ ] ncsa-mosaic
- [ ] nepaliunicode
- [ ] newlogic
- [ ] nextplayer-appimage
- [ ] nfctools
- [ ] ngpost
- [ ] ngrev
- [ ] nimbus-weather
- [ ] nordvpn-linux
- [ ] notemaster
- [ ] notepadqq
- [ ] noter
- [ ] noteshrink-qt
- [ ] ocenaudio
- [ ] ocrmypdf
- [ ] onnx2bnn
- [ ] onnx2daq
- [ ] onshape-desktop-shell
- [ ] onyx
- [ ] openarena
- [ ] osrs-tools
- [ ] outline-client-wayland | abandoned, just use simple script for disable gpu in wayland session
- [x] outline-server | dublicate of manager
- [ ] owallet
- [ ] p2p-chat
- [x] p3x-onenote | dublicate of onenote
- [ ] painel-web
- [ ] palemoon
- [ ] panini
- [ ] paper
- [ ] parallelcoin
- [ ] parity-fether
- [ ] parsec-linux-AppImage
- [ ] patchbay
- [ ] patchwork
- [ ] pathephone
- [x] pathio-alpha-bin | site is unavailable
- [x] pathio-beta-bin | site is unavailable
- [ ] patternpaint | no appimage in last releases
- [ ] pb-for-desktop
- [ ] pboy | no appimage in last releases
- [ ] pdfquirk
- [ ] pdf-sync
- [ ] photoflare | no appimage in last releases
- [ ] photoflow 
- [ ] photogimp | 2 links: diolinux: appimage is unavailable, sgmc: build is inactive
- [ ] photopea
- [ ] phototeleport
- [ ] phreshplayer
- [ ] pia
- [ ] pigs-n-cows
- [ ] pile
- [ ] pingendo
- [ ] pixsrt
- [ ] plagpatrol
- [ ] platform-tools
- [ ] playbox
- [ ] playme
- [ ] plotly-orca-appimage
- [ ] pocketcasts-electron
- [ ] poeladder
- [ ] polar-bookshelf
- [ ] polkakey
- [ ] pomotroid
- [ ] powershell
- [x] praxislive | no available appimage
- [ ] pretty-handy-privacy
- [ ] printer-client
- [ ] prospect-mail
- [ ] protoman
- [ ] proton-5.11
- [ ] protonmail-desktop
- [ ] prusacontrol
- [ ] psi+
- [ ] pullp
- [ ] pulse
- [ ] puppetry
- [ ] puush-qt
- [ ] pyappimage
- [ ] qaterialgallery
- [ ] qaterialhotreload
- [ ] qawl
- [ ] qbittorrent-lite
- [ ] qdriverstation
- [ ] qemu-ppc
- [ ] qfsm
- [ ] qikqr
- [ ] qppcad
- [ ] qr-code-generator-desktop
- [ ] qrop
- [ ] qsdrswr
- [ ] qtalarm-appImage
- [ ] qtchan
- [ ] qtjsondiff
- [x] qt-json-diff | dublicate of qtjsondiff
- [ ] qtox
- [ ] qt-raster-lines
- [ ] quark
- [ ] quicktwitch
- [ ] quokkagit
- [ ] rabix-composer
- [ ] radix-wallet
- [ ] rainbow-board
- [ ] rasterdraw
- [ ] rbdl-toolkit
- [x] rebaslight | no available appimage
- [ ] record-compare
- [ ] redminetimetracker
- [ ] reliefvalve
- [ ] rhb
- [ ] ridereceipts
- [ ] roborock-control-center
- [ ] roloviewer
- [ ] rpan-studio
- [ ] runanode
- [ ] running-dinner-tool
- [ ] safe-multisig| no available appimage, deprecated repo, now only web client
- [ ] samanager
- [ ] saucedacity | now tenacity
- [ ] sblauncher
- [ ] scatter
- [ ] scavengers
- [ ] school-sections
- [ ] sciencefair
- [ ] scraper
- [ ] screencloud
- [ ] scytale
- [ ] sentinel-dvpn-desktop | looks like abandoned, official web page suggest forks w/o releases
- [ ] ser-player
- [ ] sfrt-attendance
- [ ] shadowsocks
- [ ] shannon-Calculator
- [ ] sharemyhost
- [ ] sharp-tune
- [ ] shuttle
- [ ] sigmaspectra
- [ ] siliconsneaker
- [ ] silverkey
- [ ] simdock
- [ ] simdsp
- [ ] simplechroot
- [ ] simpleos
- [ ] simple-uploader
- [ ] simple-timer
- [ ] skrifa
- [ ] slacktronic
- [ ] slang-ed
- [ ] smartservogui
- [x] smtk2ssrf | duplicate of subsurface
- [ ] snake-js
- [ ] snippetstore
- [ ] snomcontrol
- [ ] socnetv
- [ ] software-challenge-gui
- [ ] soniclineup
- [ ] sourcetrail
- [ ] spacewars
- [ ] spark.payments
- [ ] speaky-miniplayer
- [ ] spivak
- [x] splayerx | appimage no available
- [ ] spm
- [ ] staruml | appimage no available
- [ ] statuspilatus
- [ ] steamcad
- [ ] steem-messenger
- [ ] stele
- [ ] stockstalk
- [ ] stoplight
- [ ] storaji
- [ ] strans
- [ ] strawberry
- [ ] streamon | archieved, official statement
- [ ] substrate-ide
- [ ] sumoco
- [ ] sup
- [ ] supertag
- [x] supertag-appimage | dublicate of supertag
- [ ] supertuxkart | dublicate of supertuxcart-appimage, now available appimage
- [ ] swaglyrics-appimage
- [ ] swc-minecraft-launcher
- [ ] swift
- [ ] swiftnessx
- [ ] symphonium | appimage no available
- [ ] syncmyl2p
- [ ] sys-journald
- [ ] tag-editor | appimage not found
- [ ] tagstoo
- [ ] tagtime-desktop
- [ ] taskizer
- [ ] tastee-ui
- [ ] tc
- [ ] teledrive
- [ ] Telegram-AppImage
- [ ] teslacam-browser
- [ ] textosaurus
- [ ] theframe
- [ ] thermusqt
- [ ] theweb
- [ ] thief
- [ ] thoptv
- [ ] thorium-client
- [ ] tilinggenerator
- [ ] timer
- [ ] tmon
- [ ] tnt
- [ ] todoist-linux
- [ ] tonuino-toolbox
- [ ] topgrade | no available appimage
- [ ] torrenttools
- [ ] toughcookies
- [ ] translatium | move to closed source, only snap for linux
- [ ] triagem-touch
- [ ] trinity-desktop
- [ ] tt
- [ ] ttth
- [ ] tumblr-downloader-gui
- [ ] tumblr-scraper
- [ ] tunepack-desktop
- [ ] tusk
- [ ] tweakSophia
- [ ] tweet-tray
- [ ] twetter
- [ ] twitch-wrapper
- [ ] unified-communications
- [ ] unoffical-sonos-controller
- [ ] unofficial-zalo
- [ ] unreel
- [ ] updatedeployqt
- [ ] upterm
- [ ] ventoy | no available appimage
- [ ] verto
- [ ] vessel
- [ ] viper-browser
- [ ] virtscreen
- [ ] visual-define-xml-editor
- [ ] vitomu
- [ ] vizgraph
- [ ] vk-desktop | no available appimage
- [ ] vk-music-fs
- [ ] vlc-cmatomic
- [ ] vlc-icflorescu
- [ ] vue-calc
- [ ] vuerd-electron
- [ ] wallettech
- [ ] waterfox-fourth-generation
- [ ] waterfox-third-generation
- [ ] weatherdump
- [ ] webamp
- [ ] webdesktop
- [ ] webitel-phone
- [ ] webrecorder
- [ ] westeroscraftlauncher
- [ ] wewechat
- [ ] wexond
- [ ] whatsapp-nativefier | no available appimage
- [ ] whirlpool-gui-appimage
- [ ] whiteboard
- [ ] whu-library-seat
- [ ] windows95 | no available appimage
- [ ] wine32
- [ ] wine-4.21
- [ ] wine-5.11
- [ ] wine-6.0.1
- [ ] wishdemo
- [ ] woke
- [ ] workbench
- [ ] wrapbox
- [ ] wsocks
- [ ] wxmedit | no available appimage
- [ ] XChat
- [ ] xde
- [ ] x-loc
- [ ] yuna
- [ ] zegarek
- [ ] zenkit
- [ ] zenroomstudio
- [ ] zotero | appimage is no available
- [x] zrythm | appimage is no available

### CODE REVIEW

**Comment by ivan-hc** [comment]
Just checked the list, all OK apart the lest of deletions, a lot of Appimages are available, still available or the script points to the last available release (also if the Appimage is no more developed). You should check you internet connection because you're wrong in many cases. 

Audacious, lktask, asounder.... [I'm the developer of these appimages](https://github.com/ivan-hc/Database-of-pkg2appimaged-packages ). Ark is also part of one of my appimages, i.e "[kdeutils](https://github.com/ivan-hc/KDE-utils-appimage)"! WTF!! xD

Another thing, this is the website of ALL the standalone apps, so adb and fastbot are part of platform-tools, zotero, chromium-latest.... the official version of SupertuxKart (I mantain the Appimage for x86_64, but they have a release for any architecture).

However, this is a great job. Again, you have not fount some appimages because many of them are on github, and github allows not more than 60 API-calls for hour.

I have correct some scripts. Later I'll upload them on the repository of AM, and then I'll merge this pull request. Thank you

**Review by ivan-hc — CHANGES_REQUESTED** [review]
Please, see the checklist https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io/pull/3#issue-1737465758

**Comment by ivan-hc** [comment]
Just updated the related installation scripts on "AM", now available 1743.

Now I need to upload at least the 12 files that are renamed, i.e.:

- bitbox-wallet.md
- blockstream-green.md
- compass.md
- coolercontrol.md
- defichain-app.md
- gdlauncher.md
- hapee.md
- munt.md
- play.md
- rats-search.md
- swell.md
- upscayl.md

PS: again, you've done a great job, but you've deleted too many things that are there for a reason. I've checked the related installation scripts and almost everything works great. Please be aware the next time you decide to delete something, OK?

I'm waiting that you update your fork before I close this PR, but I need those 12 files right now, because AM/AppMan and this website are one thing. 

Thank you.

**Comment by ivan-hc** [comment]
I have already done a full cleaning of the old pages no more available, but there ase still the links to change. Note that the footer in the .md files is changed, no more "Go back" but "Applications | Home" into a MD table.

**Comment by Drsheppard01** [comment]
I used force-push and the pull request closed automatically.
The main reason for deleting abandoned, archived applications is unclosed vulnerabilities, which puts the "health" of users' computers at risk

Some applications I removed by mistake (e.g. asunder, lxtask), so that there is no confusion between me and the user, I suggest to put your repository in the `source` line.

**Comment by ivan-hc** [comment]
> Some applications I removed by mistake (e.g. asunder, lxtask), so that there is no confusion between me and the user, I suggest to put your repository in the source line.

OK

> The main reason for deleting abandoned, archived applications is unclosed vulnerabilities, which puts the "health" of users' computers at risk

This is not a problem that concerns us, here we are distributing packages, good or bad they are, they exist, it is the user's discretion whether he has to pay attention to what he installs. I also wrote it in the README of the "AM" repository:

https://github.com/ivan-hc/AM-Application-Manager#known-issues

This is why I have created the option `-a` to get the pages from this sito to the terminal, `-H` to create a separated $HOME for each app, `-w` to read only the URL from these pages, `-d` to download the scripts.... and so on. I'll implement other features in my clients in the future, I just need feedbacks. And these are feature that none between apprepo.de, appimagehub.com and appimage.gith.io have! From there the people can download thing in Windows-style, with all the risks. However the user is free to install whatever he wants, at its own risk! Am  I wrong?

**Pull request closed without merging**
