### PR TITLE
update App Page

### PR DESCRIPTION
**Pull request by Drsheppard01**
Follow this issue #2

I add this strokes in template. If you like it, I will continue the work and add all the links further

### CODE REVIEW

**Comment by ivan-hc** [comment]
The template I have put there is just a sample, all the pages you see are automatically created (and a bit modified) with the option `-t` of "AM" or AppMan. Have you ever tried it? :)

PS: I like the idea of adding these things only in the template available here, but i won't implement it in my clients too, i've already done too much for these "ingrates".

**Comment by Drsheppard01** [comment]
>> Have you ever tried it? :)

Not yet, but I promise to try ;-)

**Comment by ivan-hc** [comment]
You should, it is very fun if you like to play with the bash

**Comment by Drsheppard01** [comment]
The idea is to change all apps in the repo as the template is changed. Does this need to be added?

**Pull request closed without merging**
