### PR TITLE
Fix pre, code blocks for dark theme

### PR DESCRIPTION
**Pull request by andy5995**
Follow up for #19 

I'm getting mixed results when testing, but this is what it should look like now:

image

### CODE REVIEW

**Comment by ivan-hc** [comment]
I have done xD

Istantanea_2024-10-05_15-38-14 png

the css reference is "pre"

the only thing I've not understand is how to change the background from white to (maybe) grey

**Comment by andy5995** [comment]
> the only thing I've not understand is how to change the background from white to (maybe) grey

Yes, I'm having the same problem. I'm still working on it but I think I'm about to give up for now. Thank you for helping!

**Comment by ivan-hc** [comment]
> Thank you for helping!

I'm the one who has to thank you, I had no idea how to solve the dark mode problem

**Comment by andy5995** [comment]
You already thanked me when we were chatting. :)

**Comment by ivan-hc** [comment]
should I merge this or you need to add something else?

**Comment by ivan-hc** [comment]
I have solved, take a look at the site and the css file

**Comment by ivan-hc** [comment]
> I might try to figure out how to get a black background. Let's leave this sit for now.

I analyzed the page using Firefox and followed the details about elements to check the correct CSS name, and for the backgroung its enough to use `.markdown-body` followed by the name of the element of `body`, like this
```
  hr {
    height: 0.2em;
    margin: 12px 0;
  }

  .markdown-body hr {
    background-color: #2b343f;
  }

  .markdown-body pre {
    background-color: #000;
  }

  pre {
    color: #128418;
    font-style: italic;
    font-weight: bold;
  }
```

**Comment by andy5995** [comment]
That's brilliant!

**Pull request closed without merging**
